const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..'),source=fs.readFileSync(path.join(root,'site-ads.js'),'utf8');
function run({host='typendebe.com',embedded=false,config={enabled:false},fail=false,count=1}={}){const placement={hidden:true,children:[],append(x){this.children.push(x);}},scripts=[];const placements=Array.from({length:count},()=>({...placement,children:[]}));const context={location:{hostname:host},document:{querySelectorAll:()=>placements,createElement:()=>({dataset:{}}),head:{append(x){scripts.push(x);}}},window:{NdebeAdsConfig:config}};context.window.self=context.window;context.window.top=embedded?{}:context.window;if(fail)context.window.adsbygoogle={push(){throw Error('blocked')}};vm.runInNewContext(source,context);return {placement:placements[0],placements,scripts,context};}
test('unconfigured public pages make no ad requests',()=>{const x=run();assert.equal(x.placement.hidden,true);assert.equal(x.scripts.length,0);});
test('local preview stays inert even with valid IDs',()=>{const x=run({host:'127.0.0.1',config:{enabled:true,publisher:'ca-pub-1234567890123456',slot:'1234'}});assert.equal(x.placement.hidden,false);assert.equal(x.placement.children[0].textContent,'Ad placement preview');assert.equal(x.scripts.length,0);});
test('embedded lessons never duplicate the host placement',()=>{const x=run({host:'localhost',embedded:true});assert.equal(x.placement.hidden,true);assert.equal(x.scripts.length,0);});
test('configured display unit loads once and handles blocked script',()=>{const x=run({config:{enabled:true,publisher:'ca-pub-1234567890123456',slot:'1234'}});assert.equal(x.scripts.length,1);assert.equal(x.placement.children.length,1);assert.equal(x.context.window.adsbygoogle.length,1);x.scripts[0].onerror();assert.equal(x.placement.hidden,true);});
test('every public page contains the expected placements and its assets',()=>{const pages=['index.html',...fs.readdirSync(path.join(root,'math')).filter(f=>f.endsWith('.html')).map(f=>'math/'+f),'script/index.html',...['teaching','mathematics','typing','fonts'].map(f=>'script/'+f+'/index.html')];assert.equal(pages.length,13);for(const page of pages){const s=fs.readFileSync(path.join(root,page),'utf8');assert.equal((s.match(/data-site-ad/g)||[]).length,page.startsWith('script/')?2:1,page);for(const asset of ['ads-config.js','site-ads.js','site-ads.css'])assert.ok(s.includes(asset),page);}});

test('multiple placements share one loader and each queue an ad',()=>{const x=run({count:2,config:{enabled:true,publisher:'ca-pub-1234567890123456',slot:'1234'}});assert.equal(x.scripts.length,1);assert.equal(x.context.window.adsbygoogle.length,2);for(const p of x.placements){assert.equal(p.hidden,false);assert.equal(p.children.length,1);}x.scripts[0].onerror();assert.ok(x.placements.every(p=>p.hidden));});
